### PR TITLE
Fixed #275: Clean up if hostVeth exists

### LINKED ISSUE #275: Error creating veth: failed to move veth to host netns: file exists
I use calico on kubernetes, the calico-cni version is v1.5.6. When I reboot all nodes in cluster, some of those nodes fail to create pod cause `Error creating veth: failed to move veth to host netns: file exists`.

kubelet log:

```
Feb 20 23:38:35 c4v139 kubelet[2221]: Calico CNI checking for existing endpoint: <nil>
Feb 20 23:38:35 c4v139 kubelet[2221]: time="2017-02-20T23:38:35+08:00" level=info msg="Extracted identifiers for CmdAddK8s" Node=kube-node-24 Orchestrator=k8s Workload=default.testlog038-r56dd
Feb 20 23:38:35 c4v139 kubelet[2221]: Calico CNI fetching podCidr from Kubernetes
Feb 20 23:38:35 c4v139 kubelet[2221]: time="2017-02-20T23:38:35+08:00" level=info msg="Fetched podCidr" Workload=default.testlog038-r56dd podCidr="10.100.81.0/24"
Feb 20 23:38:35 c4v139 kubelet[2221]: Calico CNI passing podCidr to host-local IPAM: 10.100.81.0/24
Feb 20 23:38:35 c4v139 kubelet[2221]: time="2017-02-20T23:38:35+08:00" level=info msg="Populated endpoint" Workload=default.testlog038-r56dd endpoint=&{{workloadEndpoint v1} {{} eth0 default.testlog038-r56dd k8s kube-node-24 map[]} {[10.100.81.10/32] [] <nil> <nil> [k8s_ns.default]  <nil>}}
Feb 20 23:38:35 c4v139 kubelet[2221]: E0220 23:38:35.080636    2221 pod_workers.go:184] Error syncing pod ecc4f431-f40b-11e6-b8b5-52540092af07, skipping: failed to "SetupNetwork" for "monitoring-server-5b2db_kube-system" with SetupNetworkError: "Failed to setup network for pod \"monitoring-server-5b2db_kube-system(ecc4f431-f40b-11e6-b8b5-52540092af07)\" using network plugins \"cni\": failed to move veth to host netns: file exists; Skipping pod"
Feb 20 23:38:35 c4v139 kubelet[2221]: time="2017-02-20T23:38:35+08:00" level=info msg="Fetched K8s labels" Workload=default.testlog038-r56dd labels=map[calico/k8s_ns:default app:testlog038]
Feb 20 23:38:35 c4v139 kubelet[2221]: Calico CNI using IPs: [10.100.81.10/32]
Feb 20 23:38:35 c4v139 kubelet[2221]: time="2017-02-20T23:38:35+08:00" level=error msg="Error creating veth: failed to move veth to host netns: file exists" Workload=default.testlog038-r56dd
Feb 20 23:38:35 c4v139 kubelet[2221]: time="2017-02-20T23:38:35+08:00" level=error msg="Error setting up networking: failed to move veth to host netns: file exists" Workload=default.testlog038-r56dd
Feb 20 23:38:35 c4v139 kubelet[2221]: time="2017-02-20T23:38:35+08:00" level=info msg="Cleaning up IP allocations for failed ADD" Workload=default.testlog038-r56dd
Feb 20 23:38:35 c4v139 kubelet[2221]: E0220 23:38:35.111156    2221 cni.go:255] Error adding network: failed to move veth to host netns: file exists
Feb 20 23:38:35 c4v139 kubelet[2221]: E0220 23:38:35.111213    2221 cni.go:209] Error while adding to cni network: failed to move veth to host netns: file exists
Feb 20 23:38:35 c4v139 kubelet[2221]: E0220 23:38:35.111265    2221 docker_manager.go:2201] Failed to setup network for pod "testlog038-r56dd_default(322cf463-f73b-11e6-9bcf-525400d8fcb5)" using network plugins "cni": failed to move veth to host netns: file exists; Skipping pod
Feb 20 23:38:35 c4v139 kubelet[2221]: E0220 23:38:35.145516    2221 pod_workers.go:184] Error syncing pod ecb02800-f40b-11e6-b8b5-52540092af07, skipping: failed to "SetupNetwork" for "kube-push-v0.0.1-88c2b_kube-system" with SetupNetworkError: "Failed to setup network for pod \"kube-push-v0.0.1-88c2b_kube-system(ecb02800-f40b-11e6-b8b5-52540092af07)\" using network plugins \"cni\": failed to move veth to host netns: file exists; Skipping pod"
Feb 20 23:38:35 c4v139 kubelet[2221]: E0220 23:38:35.175367    2221 docker_manager.go:373] NetworkPlugin cni failed on the status hook for pod 'testlog038-r56dd' - Unexpected command output nsenter: cannot open /proc/20957/ns/net: No such file or directory
Feb 20 23:38:35 c4v139 kubelet[2221]: with error: exit status 1
```

I find some extra  veth on host

```
# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:33:9d:6d brd ff:ff:ff:ff:ff:ff
    inet 192.168.16.139/20 brd 192.168.31.255 scope global ens3
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe33:9d6d/64 scope link 
       valid_lft forever preferred_lft forever
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP qlen 1000
    link/ether 52:54:00:eb:e0:9b brd ff:ff:ff:ff:ff:ff
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN 
    link/ether 02:42:79:a9:15:e9 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
5: cali010f1d6ec40@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 8a:69:e4:1c:c5:f2 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::8869:e4ff:fe1c:c5f2/64 scope link 
       valid_lft forever preferred_lft forever
6: cali61d0eeef5e9@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether aa:92:ae:dd:05:5b brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::a892:aeff:fedd:55b/64 scope link 
       valid_lft forever preferred_lft forever
7: calibee02af7915@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether ba:ae:be:24:90:36 brd ff:ff:ff:ff:ff:ff link-netnsid 2
    inet6 fe80::b8ae:beff:fe24:9036/64 scope link 
       valid_lft forever preferred_lft forever
8: calidc8adc28c03@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 5a:69:61:66:4f:68 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::5869:61ff:fe66:4f68/64 scope link 
       valid_lft forever preferred_lft forever
9: calid4ba4a79e38@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 32:37:37:c3:80:a4 brd ff:ff:ff:ff:ff:ff link-netnsid 4
    inet6 fe80::3037:37ff:fec3:80a4/64 scope link 
       valid_lft forever preferred_lft forever
10: cali30b9c92b339@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 4e:10:d4:28:91:f8 brd ff:ff:ff:ff:ff:ff link-netnsid 5
    inet6 fe80::4c10:d4ff:fe28:91f8/64 scope link 
       valid_lft forever preferred_lft forever
11: calif65d4f4f776@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether f6:06:31:33:0f:0d brd ff:ff:ff:ff:ff:ff link-netnsid 6
    inet6 fe80::f406:31ff:fe33:f0d/64 scope link 
       valid_lft forever preferred_lft forever
12: caliac561cc30ce@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether 76:34:07:ee:12:2f brd ff:ff:ff:ff:ff:ff link-netnsid 7
    inet6 fe80::7434:7ff:feee:122f/64 scope link 
       valid_lft forever preferred_lft forever
13: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN 
    link/ether 62:37:79:3f:e0:11 brd ff:ff:ff:ff:ff:ff
    inet 10.100.81.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
15: cali10fcf30e9c4@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP 
    link/ether f2:f0:b5:ff:ca:f1 brd ff:ff:ff:ff:ff:ff link-netnsid 9
    inet6 fe80::f0f0:b5ff:feff:caf1/64 scope link 
       valid_lft forever preferred_lft forever
```

route on host

```
# ip r
default via 192.168.16.1 dev ens3  proto static  metric 100 
10.100.0.0/16 dev flannel.1 
10.100.81.11 dev cali10fcf30e9c4  scope link 
172.17.0.0/16 dev docker0  proto kernel  scope link  src 172.17.0.1 
192.168.16.0/20 dev ens3  proto kernel  scope link  src 192.168.16.139  metric 100 
```

when I delete all the calixxx veth, kubelet is able to create pods. An alternative solution is restart the docker daemon.

Should calico-cni remove the extra veth on host when call `DoNetworking` failed ?

### PR DESCRIPTION
**Pull request by ijumps**
fixed issue #275

### CODE REVIEW

**Comment by caseydavenport** [comment]
This LGTM, but I'll leave it to @tomdee to make the final call.

**Comment by tomdee** [comment]
LGTM, though a test would be nice

**Comment by ijumps** [comment]
ok, I'll try to add a test later

**Comment by tomdee** [comment]
@ijumps Thanks, that would be great. I think you could manually add a veth with a conflicting name on the host, which should fail without your fix, but pass when running with your fix.

**Comment by ijumps** [comment]
@tomdee 

It's not easy to create a veth with a conflicting name, since `CreateContainer` generate and create the  veth, I'd to add the code here.

I have another idea about add the test, by creating the same container/pod twice without delete it. I have try this way, but need to change a bit more test code and more work to do.

**Comment by tomdee** [comment]
@ijumps I don't think you should create a host veth for _every_ test, you should just add a single new test which tests this new "feature"

**Comment by ijumps** [comment]
I accept that. A bit busy right now, I will discuss this on slack later ( maybe this weekend )

**Comment by ijumps** [comment]
@tomdee PTAL

**Comment by tomdee** [comment]
Looks great, thanks @ijumps

**Pull request merged**
