### PR TITLE
pin libcalico-go v1.0.0alpha.2 to fix various IPAM bugs

### PR DESCRIPTION
**Pull request by gunjan5**
pins to libcalico-go version that has cherrypicked the following bugfixes:
https://github.com/projectcalico/libcalico-go/pull/295
https://github.com/projectcalico/libcalico-go/pull/301
https://github.com/projectcalico/libcalico-go/pull/211

### CODE REVIEW

**Comment by gunjan5** [comment]
Had to modify the Makefile to add `make ci` target since semaphore settings have changed since this release.

**Comment by caseydavenport** [comment]
@gunjan5 could you update the Makefile changes to be a separate commit from pinning libcalico? Is there an appropriate cherry-pick for the makefile changes?

**Comment by gunjan5** [comment]
@caseydavenport there isn't a single change I could cherrypick for the CI target unfortunately without changing multiple targets, I can, however, add it in a separate commit.

**Comment by caseydavenport** [comment]
LGTM

**Pull request merged**
