### PR TITLE
Use glide cache to build go code

### PR DESCRIPTION
**Pull request by SergK**
* use cache as much as possible from CI user (~/.glide) also with
  fixing permissions
* add $MY_UID $MY_GID variables

We need to have an ability to run calico build in isolated environment
(without access to 3rd part repos) and cache usage is one step to this
direction

### CODE REVIEW

**Comment by SergK** [comment]
Hi, @tomdee @fasaxc could you please review this PR?

**Comment by tomdee** [comment]
I don't understand the `vendor/.up-to-date` mechanism. The intention is that `make` won't touch the vendor directory unless it doesn't exist. 

How does the `vendor/.up-to-date` file help?

**Comment by SergK** [comment]
@tomdee agree with you, will update the patch. Probably I had bad experience with directory as target in past

**Comment by tomdee** [comment]
@SergK I'm trying to move things towards using this build container https://github.com/projectcalico/go-build, I've put up PRs in the libnetwork-plugin to switch to using it, but I'm not sure when I'm going to have time to do it for calico-cni

**Comment by SergK** [comment]
@tomdee thank you, yep I've already seen `go-build` cool. Please let me know if you have some working prototype (approach, PR) then I'll try to align cni make code

**Comment by SergK** [comment]
Ok, I see pull requests https://github.com/projectcalico/libnetwork-plugin/pulls ok I will wait the general concept to be merged and can help with cni as well

**Comment by tomdee** [comment]
@SergK BTW The libnetwork-plugin PR was merged

**Comment by SergK** [comment]
@tomdee thank you, closing this issue

**Pull request closed without merging**
