### PR TITLE
fix: specify platform in docker build command

### PR DESCRIPTION
**Pull request by chewong**
## Description

The image architecture is inconsistent with the tag name, e.g.

```
docker manifest inspect --verbose quay.io/calico/cni:master-arm64
{
	"Ref": "quay.io/calico/cni:master-arm64",
	"Descriptor": {
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"digest": "sha256:e7caadcff3cf791a643778c70f0d5a6d9231daca9d077c85efcb32346381773e",
		"size": 946,
		"platform": {
			"architecture": "amd64",
			"os": "linux"
		}
	},
...
```

After specifying `--platform` to `docker build` command:

```
docker manifest inspect --verbose chewong/cni:master-arm64
{
	"Ref": "upstream.azurecr.io/oss/calico/cni:docker-build-platform-linux-arm64",
	"Descriptor": {
		"mediaType": "application/vnd.docker.distribution.manifest.v2+json",
		"digest": "sha256:adee1446177b219ace6ff2900c667d9637038f24ebaef9257232570b0de69359",
		"size": 739,
		"platform": {
			"architecture": "arm64",
			"os": "linux"
		}
	},
...
```

## Todos
- [x] Tests
- [x] Documentation
- [x] Release note

## Release Note

```release-note
Fix multi-arch builds for cni-plugin by specifying platform. 
```

### CODE REVIEW

**Review by caseydavenport — DISMISSED** [review]
@frozenprocess could you double check this? Looks right to me

**Comment by frozenprocess** [comment]
@chewong `image-all` is still broken :(
```
Step 3/8 : ADD licenses/ /licenses
failed to get destination image "sha256:470cdfed2b7ec6f3970279fba418bc38cc6e1def5532ace2972f7ce081b2dd97": image with reference sha256:470cdfed2b7ec6f3970279fba418bc38cc6e1def5532ace2972f7ce081b2dd97 was found but does not match the specified platform: wanted linux/ppc64le, actual: linux/amd64
make[1]: *** [Makefile:146: cni_deploy_container-ppc64le.created] Error 1
make[1]: Leaving directory '/home/calico/cni-plugin'
make: *** [Makefile:143: sub-image-ppc64le] Error 2
```

**Comment by caseydavenport** [comment]
The Calico team is reorganizing our code and repository structure in order to make development easier, and as such all of the code in this repository is now located at https://github.com/projectcalico/calico. We appreciate your PR and your patience as we work to improve our developer experience, and welcome you to re-open your changes against the new location. Please reach out if you have any questions!

**Pull request closed without merging**
