### PR TITLE
Add portmap plugin

### PR DESCRIPTION
**Pull request by caseydavenport**
## Description
Adds the portmap plugin from https://github.com/containernetworking/plugins/pull/1 to the cni installer.  Currently, there is no release of the portmap plugin so this PR needs to wait until there is one.

## Todos
- [x] Include portmap plugin, or reference upstream release.
- [ ] Documentation

### CODE REVIEW

**Comment by tomdee** [comment]
I'm not super stoked about having that binary checked in, since it will live in the history forever. But otherwise, the change looks fine.

**Comment by tomdee** [comment]
Actually - please also say (somewhere) exactly what git hash the binary is built from.

**Comment by gunjan5** [comment]
What's wrong with leaving it as a Dockerhub image (with binary in it) until the plugin PR is merged so we don't have to upload the binary to the repo?

**Comment by caseydavenport** [comment]
> What's wrong with leaving it as a Dockerhub image (with binary in it) until the plugin PR is merged so we don't have to upload the binary to the repo?

We could do that.  It would mean that building that version of the calico/cni container wouldn't be reproducible (but we could include the commit hash from which it was built to make that easier?)

**Pull request merged**
